# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
podfile: Example/Podfile
cache: cocoapods

script: cd Example ; set -o pipefail && xcodebuild -workspace 'RxAppState.xcworkspace' -scheme 'RxAppState-Example' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='9.1',name='iPhone 6s' build test | xcpretty -c --test
